version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Aeturnis-Development-Labs-LLC/maintainers"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "pytest"
        update-types: ["version-update:semver-major"]
      - dependency-name: "mypy"
        update-types: ["version-update:semver-major"]
    groups:
      # Group all development dependencies together
      dev-dependencies:
        patterns:
          - "pytest*"
          - "flake8*"
          - "black"
          - "isort"
          - "mypy"
          - "bandit"
          - "pre-commit"
      # Group all type stubs together
      type-stubs:
        patterns:
          - "types-*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    reviewers:
      - "Aeturnis-Development-Labs-LLC/maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
