# Codecov configuration
coverage:
  status:
    project:
      default:
        # Only fail if coverage drops by more than 2%
        threshold: 2%
        target: auto
    patch:
      default:
        # New code should have at least 80% coverage
        target: 80%
        threshold: 2%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true  # Only comment if coverage changes

# Ignore test files and __init__.py files
ignore:
  - "tests/**"
  - "**/__init__.py"
  - "scripts/**"